name             'spark'
maintainer       'Passworks'
maintainer_email 'luis.alves@passworks.io'
license          'All rights reserved'
description      'Cookbook to install/launch a cluster of spark 1.4.1'
version          '0.1.0'
