---
driver:
  name: vagrant

provisioner:
  name: chef_zero # chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[lighthouse::default]
    attributes:
